name: "ğŸ§ª CI"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NODE_ENV: test
  NODE_VERSION: 18.x  # ref: https://nodejs.org/en/about/releases/

jobs:
  lint_test_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ğŸ”§ Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: ğŸ“¦ Install Dependencies
        uses: bahmutov/npm-install@v1 # https://github.com/bahmutov/npm-install

      - name: ğŸ” Lint files
        run: yarn run lint

      - name: ğŸ§ª  Run unit tests
        run: yarn test

      - name: ğŸ— Build
        run: yarn run build

      